# docker-compose-app.yml
version: "3.9"

services:
  springboot-app:
    build:
      context: .
      dockerfile: services/Dockerfiles/api/Dockerfile
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pdf_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - backend

    volumes:
      - /home/stojani/Downloads:/mnt/Downloads
networks:
  backend:
    external: true
